platform :ios, '13.0'
use_frameworks!

target 'ExpoExample' do
  # Test modular headers installation for Expo compatibility
  pod 'GoogleNearbyPod', :path => '../../..', :modular_headers => true
  pod 'BoringSSL-GRPC', :modular_headers => true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end 