platform :ios, '13.0'
use_frameworks!

target 'TestApp' do
  # Use local path for testing - no GitHub repo needed
  pod 'GoogleNearbyPod', :path => '../../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end 